#!/bin/bash
export __GL_SYNC_TO_VBLANK=0
export __NV_PRIME_RENDER_OFFLOAD=1
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only

# Dynamic expansion of all nvidia_icd*.json files
export VK_ICD_FILENAMES=$(find /usr/share/vulkan/icd.d/ -name "nvidia_icd*.json" | paste -sd: -)

exec "$@"