#!/bin/bash
echo 'Performing system update'
sudo dnf update -y
if [ -x /usr/bin/flatpak ]
then
    echo 'Performing flatpaks update'
    flatpak update -y
fi
if [ -x /usr/sbin/akmods-shutdown ]
then            
    echo 'Rebuilding akmods, please wait'
    sudo akmods-shutdown
fi