#!/bin/bash

GS_ARGS=()
COMMAND=()
FOUND_SEPARATOR=false

for arg in "$@"; do
  if [[ "$arg" == "--" && "$FOUND_SEPARATOR" == false ]]; then
    FOUND_SEPARATOR=true
    continue
  fi

  if [[ "$FOUND_SEPARATOR" == true ]]; then
    COMMAND+=("$arg")
  else
    GS_ARGS+=("$arg")
  fi
done

# Safety check: if no -- was provided, the whole thing is GS_ARGS
# You might want to handle that case depending on your Steam launch options.

gamescope "${GS_ARGS[@]}" -- "${COMMAND[@]}" &
GS_PID=$!

wait $GS_PID

# Clean up
killall -9 -u $(whoami) gamescopereaper gamescope 2>/dev/null